# Generated by Django 5.1 on 2025-12-21 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0015_alter_student_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dormitory',
            name='captain',
        ),
        migrations.RemoveField(
            model_name='dormitoryallocation',
            name='dormitory',
        ),
        migrations.RemoveField(
            model_name='dormitoryallocation',
            name='student',
        ),
        migrations.DeleteModel(
            name='MessageToParent',
        ),
        migrations.DeleteModel(
            name='MessageToTeacher',
        ),
        migrations.RemoveField(
            model_name='studenthealthrecord',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentsmedicalhistory',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentspreviousacademichistory',
            name='student',
        ),
        migrations.DeleteModel(
            name='Dormitory',
        ),
        migrations.DeleteModel(
            name='DormitoryAllocation',
        ),
        migrations.DeleteModel(
            name='StudentHealthRecord',
        ),
        migrations.DeleteModel(
            name='StudentsMedicalHistory',
        ),
        migrations.DeleteModel(
            name='StudentsPreviousAcademicHistory',
        ),
    ]
